//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Es.Udc.DotNet.WebMovies.Model", "LinkLabel", "Label", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.WebMovies.Model.Label), "Link", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.WebMovies.Model.Link))]
[assembly: EdmRelationshipAttribute("Es.Udc.DotNet.WebMovies.Model", "FK_Comment_LinkId", "Link", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Es.Udc.DotNet.WebMovies.Model.Link), "Comment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.WebMovies.Model.Comment), true)]
[assembly: EdmRelationshipAttribute("Es.Udc.DotNet.WebMovies.Model", "FK_Comment_UsrId", "UserProfile", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Es.Udc.DotNet.WebMovies.Model.UserProfile), "Comment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.WebMovies.Model.Comment), true)]
[assembly: EdmRelationshipAttribute("Es.Udc.DotNet.WebMovies.Model", "FK_Favorite_LinkId", "Link", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Es.Udc.DotNet.WebMovies.Model.Link), "Favorite", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.WebMovies.Model.Favorite), true)]
[assembly: EdmRelationshipAttribute("Es.Udc.DotNet.WebMovies.Model", "FK_Favorite_UsrId", "UserProfile", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Es.Udc.DotNet.WebMovies.Model.UserProfile), "Favorite", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.WebMovies.Model.Favorite), true)]
[assembly: EdmRelationshipAttribute("Es.Udc.DotNet.WebMovies.Model", "FK_Link_UsrId", "UserProfile", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Es.Udc.DotNet.WebMovies.Model.UserProfile), "Link", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.WebMovies.Model.Link), true)]
[assembly: EdmRelationshipAttribute("Es.Udc.DotNet.WebMovies.Model", "FK_Rating_LinkId", "Link", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Es.Udc.DotNet.WebMovies.Model.Link), "Rating", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.WebMovies.Model.Rating), true)]
[assembly: EdmRelationshipAttribute("Es.Udc.DotNet.WebMovies.Model", "FK_Rating_UsrId", "UserProfile", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Es.Udc.DotNet.WebMovies.Model.UserProfile), "Rating", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.WebMovies.Model.Rating), true)]
[assembly: EdmRelationshipAttribute("Es.Udc.DotNet.WebMovies.Model", "LanguageCountry", "Country", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.WebMovies.Model.Country), "Language", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.WebMovies.Model.Language))]
[assembly: EdmRelationshipAttribute("Es.Udc.DotNet.WebMovies.Model", "FK_UserProfile_Country", "Country", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Es.Udc.DotNet.WebMovies.Model.Country), "UserProfile", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.WebMovies.Model.UserProfile), true)]
[assembly: EdmRelationshipAttribute("Es.Udc.DotNet.WebMovies.Model", "FK_UserProfile_Language", "Language", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Es.Udc.DotNet.WebMovies.Model.Language), "UserProfile", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.WebMovies.Model.UserProfile), true)]

#endregion

namespace Es.Udc.DotNet.WebMovies.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class WebMoviesEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new WebMoviesEntities object using the connection string found in the 'WebMoviesEntities' section of the application configuration file.
        /// </summary>
        public WebMoviesEntities() : base("name=WebMoviesEntities", "WebMoviesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new WebMoviesEntities object.
        /// </summary>
        public WebMoviesEntities(string connectionString) : base(connectionString, "WebMoviesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new WebMoviesEntities object.
        /// </summary>
        public WebMoviesEntities(EntityConnection connection) : base(connection, "WebMoviesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Comment> Comment
        {
            get
            {
                if ((_Comment == null))
                {
                    _Comment = base.CreateObjectSet<Comment>("Comment");
                }
                return _Comment;
            }
        }
        private ObjectSet<Comment> _Comment;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Country> Country
        {
            get
            {
                if ((_Country == null))
                {
                    _Country = base.CreateObjectSet<Country>("Country");
                }
                return _Country;
            }
        }
        private ObjectSet<Country> _Country;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Favorite> Favorite
        {
            get
            {
                if ((_Favorite == null))
                {
                    _Favorite = base.CreateObjectSet<Favorite>("Favorite");
                }
                return _Favorite;
            }
        }
        private ObjectSet<Favorite> _Favorite;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Label> Label
        {
            get
            {
                if ((_Label == null))
                {
                    _Label = base.CreateObjectSet<Label>("Label");
                }
                return _Label;
            }
        }
        private ObjectSet<Label> _Label;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Language> Language
        {
            get
            {
                if ((_Language == null))
                {
                    _Language = base.CreateObjectSet<Language>("Language");
                }
                return _Language;
            }
        }
        private ObjectSet<Language> _Language;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Link> Link
        {
            get
            {
                if ((_Link == null))
                {
                    _Link = base.CreateObjectSet<Link>("Link");
                }
                return _Link;
            }
        }
        private ObjectSet<Link> _Link;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Rating> Rating
        {
            get
            {
                if ((_Rating == null))
                {
                    _Rating = base.CreateObjectSet<Rating>("Rating");
                }
                return _Rating;
            }
        }
        private ObjectSet<Rating> _Rating;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UserProfile> UserProfile
        {
            get
            {
                if ((_UserProfile == null))
                {
                    _UserProfile = base.CreateObjectSet<UserProfile>("UserProfile");
                }
                return _UserProfile;
            }
        }
        private ObjectSet<UserProfile> _UserProfile;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Comment EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToComment(Comment comment)
        {
            base.AddObject("Comment", comment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Country EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCountry(Country country)
        {
            base.AddObject("Country", country);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Favorite EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFavorite(Favorite favorite)
        {
            base.AddObject("Favorite", favorite);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Label EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLabel(Label label)
        {
            base.AddObject("Label", label);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Language EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLanguage(Language language)
        {
            base.AddObject("Language", language);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Link EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLink(Link link)
        {
            base.AddObject("Link", link);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Rating EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRating(Rating rating)
        {
            base.AddObject("Rating", rating);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UserProfile EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUserProfile(UserProfile userProfile)
        {
            base.AddObject("UserProfile", userProfile);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Es.Udc.DotNet.WebMovies.Model", Name="Comment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Comment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Comment object.
        /// </summary>
        /// <param name="commentId">Initial value of the commentId property.</param>
        /// <param name="userId">Initial value of the userId property.</param>
        /// <param name="linkId">Initial value of the linkId property.</param>
        /// <param name="text">Initial value of the text property.</param>
        /// <param name="date">Initial value of the date property.</param>
        public static Comment CreateComment(global::System.Int64 commentId, global::System.Int64 userId, global::System.Int64 linkId, global::System.String text, global::System.DateTime date)
        {
            Comment comment = new Comment();
            comment.commentId = commentId;
            comment.userId = userId;
            comment.linkId = linkId;
            comment.text = text;
            comment.date = date;
            return comment;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 commentId
        {
            get
            {
                return _commentId;
            }
            set
            {
                if (_commentId != value)
                {
                    OncommentIdChanging(value);
                    ReportPropertyChanging("commentId");
                    _commentId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("commentId");
                    OncommentIdChanged();
                }
            }
        }
        private global::System.Int64 _commentId;
        partial void OncommentIdChanging(global::System.Int64 value);
        partial void OncommentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 userId
        {
            get
            {
                return _userId;
            }
            set
            {
                OnuserIdChanging(value);
                ReportPropertyChanging("userId");
                _userId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("userId");
                OnuserIdChanged();
            }
        }
        private global::System.Int64 _userId;
        partial void OnuserIdChanging(global::System.Int64 value);
        partial void OnuserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 linkId
        {
            get
            {
                return _linkId;
            }
            set
            {
                OnlinkIdChanging(value);
                ReportPropertyChanging("linkId");
                _linkId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("linkId");
                OnlinkIdChanged();
            }
        }
        private global::System.Int64 _linkId;
        partial void OnlinkIdChanging(global::System.Int64 value);
        partial void OnlinkIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String text
        {
            get
            {
                return _text;
            }
            set
            {
                OntextChanging(value);
                ReportPropertyChanging("text");
                _text = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("text");
                OntextChanged();
            }
        }
        private global::System.String _text;
        partial void OntextChanging(global::System.String value);
        partial void OntextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime date
        {
            get
            {
                return _date;
            }
            set
            {
                OndateChanging(value);
                ReportPropertyChanging("date");
                _date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date");
                OndateChanged();
            }
        }
        private global::System.DateTime _date;
        partial void OndateChanging(global::System.DateTime value);
        partial void OndateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.WebMovies.Model", "FK_Comment_UsrId", "UserProfile")]
        public UserProfile UserProfile
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("Es.Udc.DotNet.WebMovies.Model.FK_Comment_UsrId", "UserProfile").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("Es.Udc.DotNet.WebMovies.Model.FK_Comment_UsrId", "UserProfile").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UserProfile> UserProfileReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("Es.Udc.DotNet.WebMovies.Model.FK_Comment_UsrId", "UserProfile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UserProfile>("Es.Udc.DotNet.WebMovies.Model.FK_Comment_UsrId", "UserProfile", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.WebMovies.Model", "FK_Comment_LinkId", "Link")]
        public Link Link
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Link>("Es.Udc.DotNet.WebMovies.Model.FK_Comment_LinkId", "Link").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Link>("Es.Udc.DotNet.WebMovies.Model.FK_Comment_LinkId", "Link").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Link> LinkReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Link>("Es.Udc.DotNet.WebMovies.Model.FK_Comment_LinkId", "Link");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Link>("Es.Udc.DotNet.WebMovies.Model.FK_Comment_LinkId", "Link", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Es.Udc.DotNet.WebMovies.Model", Name="Country")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Country : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Country object.
        /// </summary>
        /// <param name="countryCode">Initial value of the countryCode property.</param>
        /// <param name="countryName">Initial value of the countryName property.</param>
        public static Country CreateCountry(global::System.String countryCode, global::System.String countryName)
        {
            Country country = new Country();
            country.countryCode = countryCode;
            country.countryName = countryName;
            return country;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String countryCode
        {
            get
            {
                return _countryCode;
            }
            set
            {
                if (_countryCode != value)
                {
                    OncountryCodeChanging(value);
                    ReportPropertyChanging("countryCode");
                    _countryCode = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("countryCode");
                    OncountryCodeChanged();
                }
            }
        }
        private global::System.String _countryCode;
        partial void OncountryCodeChanging(global::System.String value);
        partial void OncountryCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String countryName
        {
            get
            {
                return _countryName;
            }
            set
            {
                OncountryNameChanging(value);
                ReportPropertyChanging("countryName");
                _countryName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("countryName");
                OncountryNameChanged();
            }
        }
        private global::System.String _countryName;
        partial void OncountryNameChanging(global::System.String value);
        partial void OncountryNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.WebMovies.Model", "LanguageCountry", "Language")]
        public EntityCollection<Language> Languages
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Language>("Es.Udc.DotNet.WebMovies.Model.LanguageCountry", "Language");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Language>("Es.Udc.DotNet.WebMovies.Model.LanguageCountry", "Language", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.WebMovies.Model", "FK_UserProfile_Country", "UserProfile")]
        public EntityCollection<UserProfile> UserProfiles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UserProfile>("Es.Udc.DotNet.WebMovies.Model.FK_UserProfile_Country", "UserProfile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UserProfile>("Es.Udc.DotNet.WebMovies.Model.FK_UserProfile_Country", "UserProfile", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Es.Udc.DotNet.WebMovies.Model", Name="Favorite")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Favorite : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Favorite object.
        /// </summary>
        /// <param name="favoriteId">Initial value of the favoriteId property.</param>
        /// <param name="userId">Initial value of the userId property.</param>
        /// <param name="linkId">Initial value of the linkId property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="description">Initial value of the description property.</param>
        /// <param name="date">Initial value of the date property.</param>
        public static Favorite CreateFavorite(global::System.Int64 favoriteId, global::System.Int64 userId, global::System.Int64 linkId, global::System.String name, global::System.String description, global::System.DateTime date)
        {
            Favorite favorite = new Favorite();
            favorite.favoriteId = favoriteId;
            favorite.userId = userId;
            favorite.linkId = linkId;
            favorite.name = name;
            favorite.description = description;
            favorite.date = date;
            return favorite;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 favoriteId
        {
            get
            {
                return _favoriteId;
            }
            set
            {
                if (_favoriteId != value)
                {
                    OnfavoriteIdChanging(value);
                    ReportPropertyChanging("favoriteId");
                    _favoriteId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("favoriteId");
                    OnfavoriteIdChanged();
                }
            }
        }
        private global::System.Int64 _favoriteId;
        partial void OnfavoriteIdChanging(global::System.Int64 value);
        partial void OnfavoriteIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 userId
        {
            get
            {
                return _userId;
            }
            set
            {
                OnuserIdChanging(value);
                ReportPropertyChanging("userId");
                _userId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("userId");
                OnuserIdChanged();
            }
        }
        private global::System.Int64 _userId;
        partial void OnuserIdChanging(global::System.Int64 value);
        partial void OnuserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 linkId
        {
            get
            {
                return _linkId;
            }
            set
            {
                OnlinkIdChanging(value);
                ReportPropertyChanging("linkId");
                _linkId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("linkId");
                OnlinkIdChanged();
            }
        }
        private global::System.Int64 _linkId;
        partial void OnlinkIdChanging(global::System.Int64 value);
        partial void OnlinkIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime date
        {
            get
            {
                return _date;
            }
            set
            {
                OndateChanging(value);
                ReportPropertyChanging("date");
                _date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date");
                OndateChanged();
            }
        }
        private global::System.DateTime _date;
        partial void OndateChanging(global::System.DateTime value);
        partial void OndateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.WebMovies.Model", "FK_Favorite_UsrId", "UserProfile")]
        public UserProfile UserProfile
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("Es.Udc.DotNet.WebMovies.Model.FK_Favorite_UsrId", "UserProfile").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("Es.Udc.DotNet.WebMovies.Model.FK_Favorite_UsrId", "UserProfile").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UserProfile> UserProfileReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("Es.Udc.DotNet.WebMovies.Model.FK_Favorite_UsrId", "UserProfile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UserProfile>("Es.Udc.DotNet.WebMovies.Model.FK_Favorite_UsrId", "UserProfile", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.WebMovies.Model", "FK_Favorite_LinkId", "Link")]
        public Link Link
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Link>("Es.Udc.DotNet.WebMovies.Model.FK_Favorite_LinkId", "Link").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Link>("Es.Udc.DotNet.WebMovies.Model.FK_Favorite_LinkId", "Link").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Link> LinkReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Link>("Es.Udc.DotNet.WebMovies.Model.FK_Favorite_LinkId", "Link");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Link>("Es.Udc.DotNet.WebMovies.Model.FK_Favorite_LinkId", "Link", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Es.Udc.DotNet.WebMovies.Model", Name="Label")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Label : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Label object.
        /// </summary>
        /// <param name="labelId">Initial value of the labelId property.</param>
        /// <param name="text">Initial value of the text property.</param>
        public static Label CreateLabel(global::System.Int64 labelId, global::System.String text)
        {
            Label label = new Label();
            label.labelId = labelId;
            label.text = text;
            return label;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 labelId
        {
            get
            {
                return _labelId;
            }
            set
            {
                if (_labelId != value)
                {
                    OnlabelIdChanging(value);
                    ReportPropertyChanging("labelId");
                    _labelId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("labelId");
                    OnlabelIdChanged();
                }
            }
        }
        private global::System.Int64 _labelId;
        partial void OnlabelIdChanging(global::System.Int64 value);
        partial void OnlabelIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String text
        {
            get
            {
                return _text;
            }
            set
            {
                OntextChanging(value);
                ReportPropertyChanging("text");
                _text = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("text");
                OntextChanged();
            }
        }
        private global::System.String _text;
        partial void OntextChanging(global::System.String value);
        partial void OntextChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.WebMovies.Model", "LinkLabel", "Link")]
        public EntityCollection<Link> Links
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Link>("Es.Udc.DotNet.WebMovies.Model.LinkLabel", "Link");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Link>("Es.Udc.DotNet.WebMovies.Model.LinkLabel", "Link", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Es.Udc.DotNet.WebMovies.Model", Name="Language")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Language : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Language object.
        /// </summary>
        /// <param name="languageCode">Initial value of the languageCode property.</param>
        /// <param name="languageName">Initial value of the languageName property.</param>
        public static Language CreateLanguage(global::System.String languageCode, global::System.String languageName)
        {
            Language language = new Language();
            language.languageCode = languageCode;
            language.languageName = languageName;
            return language;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String languageCode
        {
            get
            {
                return _languageCode;
            }
            set
            {
                if (_languageCode != value)
                {
                    OnlanguageCodeChanging(value);
                    ReportPropertyChanging("languageCode");
                    _languageCode = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("languageCode");
                    OnlanguageCodeChanged();
                }
            }
        }
        private global::System.String _languageCode;
        partial void OnlanguageCodeChanging(global::System.String value);
        partial void OnlanguageCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String languageName
        {
            get
            {
                return _languageName;
            }
            set
            {
                OnlanguageNameChanging(value);
                ReportPropertyChanging("languageName");
                _languageName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("languageName");
                OnlanguageNameChanged();
            }
        }
        private global::System.String _languageName;
        partial void OnlanguageNameChanging(global::System.String value);
        partial void OnlanguageNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.WebMovies.Model", "LanguageCountry", "Country")]
        public EntityCollection<Country> Countries
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Country>("Es.Udc.DotNet.WebMovies.Model.LanguageCountry", "Country");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Country>("Es.Udc.DotNet.WebMovies.Model.LanguageCountry", "Country", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.WebMovies.Model", "FK_UserProfile_Language", "UserProfile")]
        public EntityCollection<UserProfile> UserProfiles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UserProfile>("Es.Udc.DotNet.WebMovies.Model.FK_UserProfile_Language", "UserProfile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UserProfile>("Es.Udc.DotNet.WebMovies.Model.FK_UserProfile_Language", "UserProfile", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Es.Udc.DotNet.WebMovies.Model", Name="Link")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Link : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Link object.
        /// </summary>
        /// <param name="linkId">Initial value of the linkId property.</param>
        /// <param name="movieId">Initial value of the movieId property.</param>
        /// <param name="userId">Initial value of the userId property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="description">Initial value of the description property.</param>
        /// <param name="url">Initial value of the url property.</param>
        /// <param name="date">Initial value of the date property.</param>
        public static Link CreateLink(global::System.Int64 linkId, global::System.Int64 movieId, global::System.Int64 userId, global::System.String name, global::System.String description, global::System.String url, global::System.DateTime date)
        {
            Link link = new Link();
            link.linkId = linkId;
            link.movieId = movieId;
            link.userId = userId;
            link.name = name;
            link.description = description;
            link.url = url;
            link.date = date;
            return link;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 linkId
        {
            get
            {
                return _linkId;
            }
            set
            {
                if (_linkId != value)
                {
                    OnlinkIdChanging(value);
                    ReportPropertyChanging("linkId");
                    _linkId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("linkId");
                    OnlinkIdChanged();
                }
            }
        }
        private global::System.Int64 _linkId;
        partial void OnlinkIdChanging(global::System.Int64 value);
        partial void OnlinkIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 movieId
        {
            get
            {
                return _movieId;
            }
            set
            {
                OnmovieIdChanging(value);
                ReportPropertyChanging("movieId");
                _movieId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("movieId");
                OnmovieIdChanged();
            }
        }
        private global::System.Int64 _movieId;
        partial void OnmovieIdChanging(global::System.Int64 value);
        partial void OnmovieIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 userId
        {
            get
            {
                return _userId;
            }
            set
            {
                OnuserIdChanging(value);
                ReportPropertyChanging("userId");
                _userId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("userId");
                OnuserIdChanged();
            }
        }
        private global::System.Int64 _userId;
        partial void OnuserIdChanging(global::System.Int64 value);
        partial void OnuserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String url
        {
            get
            {
                return _url;
            }
            set
            {
                OnurlChanging(value);
                ReportPropertyChanging("url");
                _url = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("url");
                OnurlChanged();
            }
        }
        private global::System.String _url;
        partial void OnurlChanging(global::System.String value);
        partial void OnurlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> reportRead
        {
            get
            {
                return _reportRead;
            }
            set
            {
                OnreportReadChanging(value);
                ReportPropertyChanging("reportRead");
                _reportRead = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("reportRead");
                OnreportReadChanged();
            }
        }
        private Nullable<global::System.Boolean> _reportRead;
        partial void OnreportReadChanging(Nullable<global::System.Boolean> value);
        partial void OnreportReadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime date
        {
            get
            {
                return _date;
            }
            set
            {
                OndateChanging(value);
                ReportPropertyChanging("date");
                _date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date");
                OndateChanged();
            }
        }
        private global::System.DateTime _date;
        partial void OndateChanging(global::System.DateTime value);
        partial void OndateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.WebMovies.Model", "FK_Link_UsrId", "UserProfile")]
        public UserProfile UserProfile
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("Es.Udc.DotNet.WebMovies.Model.FK_Link_UsrId", "UserProfile").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("Es.Udc.DotNet.WebMovies.Model.FK_Link_UsrId", "UserProfile").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UserProfile> UserProfileReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("Es.Udc.DotNet.WebMovies.Model.FK_Link_UsrId", "UserProfile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UserProfile>("Es.Udc.DotNet.WebMovies.Model.FK_Link_UsrId", "UserProfile", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.WebMovies.Model", "LinkLabel", "Label")]
        public EntityCollection<Label> Labels
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Label>("Es.Udc.DotNet.WebMovies.Model.LinkLabel", "Label");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Label>("Es.Udc.DotNet.WebMovies.Model.LinkLabel", "Label", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.WebMovies.Model", "FK_Rating_LinkId", "Rating")]
        public EntityCollection<Rating> Ratings
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Rating>("Es.Udc.DotNet.WebMovies.Model.FK_Rating_LinkId", "Rating");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Rating>("Es.Udc.DotNet.WebMovies.Model.FK_Rating_LinkId", "Rating", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.WebMovies.Model", "FK_Comment_LinkId", "Comment")]
        public EntityCollection<Comment> Comments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Comment>("Es.Udc.DotNet.WebMovies.Model.FK_Comment_LinkId", "Comment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Comment>("Es.Udc.DotNet.WebMovies.Model.FK_Comment_LinkId", "Comment", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.WebMovies.Model", "FK_Favorite_LinkId", "Favorite")]
        public EntityCollection<Favorite> Favorites
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Favorite>("Es.Udc.DotNet.WebMovies.Model.FK_Favorite_LinkId", "Favorite");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Favorite>("Es.Udc.DotNet.WebMovies.Model.FK_Favorite_LinkId", "Favorite", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Es.Udc.DotNet.WebMovies.Model", Name="Rating")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Rating : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Rating object.
        /// </summary>
        /// <param name="ratingId">Initial value of the ratingId property.</param>
        /// <param name="userId">Initial value of the userId property.</param>
        /// <param name="linkId">Initial value of the linkId property.</param>
        /// <param name="value">Initial value of the value property.</param>
        /// <param name="date">Initial value of the date property.</param>
        public static Rating CreateRating(global::System.Int64 ratingId, global::System.Int64 userId, global::System.Int64 linkId, global::System.Int32 value, global::System.DateTime date)
        {
            Rating rating = new Rating();
            rating.ratingId = ratingId;
            rating.userId = userId;
            rating.linkId = linkId;
            rating.value = value;
            rating.date = date;
            return rating;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ratingId
        {
            get
            {
                return _ratingId;
            }
            set
            {
                if (_ratingId != value)
                {
                    OnratingIdChanging(value);
                    ReportPropertyChanging("ratingId");
                    _ratingId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ratingId");
                    OnratingIdChanged();
                }
            }
        }
        private global::System.Int64 _ratingId;
        partial void OnratingIdChanging(global::System.Int64 value);
        partial void OnratingIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 userId
        {
            get
            {
                return _userId;
            }
            set
            {
                OnuserIdChanging(value);
                ReportPropertyChanging("userId");
                _userId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("userId");
                OnuserIdChanged();
            }
        }
        private global::System.Int64 _userId;
        partial void OnuserIdChanging(global::System.Int64 value);
        partial void OnuserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 linkId
        {
            get
            {
                return _linkId;
            }
            set
            {
                OnlinkIdChanging(value);
                ReportPropertyChanging("linkId");
                _linkId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("linkId");
                OnlinkIdChanged();
            }
        }
        private global::System.Int64 _linkId;
        partial void OnlinkIdChanging(global::System.Int64 value);
        partial void OnlinkIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 value
        {
            get
            {
                return _value;
            }
            set
            {
                OnvalueChanging(value);
                ReportPropertyChanging("value");
                _value = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("value");
                OnvalueChanged();
            }
        }
        private global::System.Int32 _value;
        partial void OnvalueChanging(global::System.Int32 value);
        partial void OnvalueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime date
        {
            get
            {
                return _date;
            }
            set
            {
                OndateChanging(value);
                ReportPropertyChanging("date");
                _date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date");
                OndateChanged();
            }
        }
        private global::System.DateTime _date;
        partial void OndateChanging(global::System.DateTime value);
        partial void OndateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.WebMovies.Model", "FK_Rating_UsrId", "UserProfile")]
        public UserProfile UserProfile
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("Es.Udc.DotNet.WebMovies.Model.FK_Rating_UsrId", "UserProfile").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("Es.Udc.DotNet.WebMovies.Model.FK_Rating_UsrId", "UserProfile").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UserProfile> UserProfileReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("Es.Udc.DotNet.WebMovies.Model.FK_Rating_UsrId", "UserProfile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UserProfile>("Es.Udc.DotNet.WebMovies.Model.FK_Rating_UsrId", "UserProfile", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.WebMovies.Model", "FK_Rating_LinkId", "Link")]
        public Link Link
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Link>("Es.Udc.DotNet.WebMovies.Model.FK_Rating_LinkId", "Link").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Link>("Es.Udc.DotNet.WebMovies.Model.FK_Rating_LinkId", "Link").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Link> LinkReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Link>("Es.Udc.DotNet.WebMovies.Model.FK_Rating_LinkId", "Link");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Link>("Es.Udc.DotNet.WebMovies.Model.FK_Rating_LinkId", "Link", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Es.Udc.DotNet.WebMovies.Model", Name="UserProfile")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserProfile : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UserProfile object.
        /// </summary>
        /// <param name="userId">Initial value of the userId property.</param>
        /// <param name="userLogin">Initial value of the userLogin property.</param>
        /// <param name="password">Initial value of the password property.</param>
        /// <param name="firstName">Initial value of the firstName property.</param>
        /// <param name="lastName">Initial value of the lastName property.</param>
        /// <param name="email">Initial value of the email property.</param>
        /// <param name="languageCode">Initial value of the languageCode property.</param>
        /// <param name="countryCode">Initial value of the countryCode property.</param>
        public static UserProfile CreateUserProfile(global::System.Int64 userId, global::System.String userLogin, global::System.String password, global::System.String firstName, global::System.String lastName, global::System.String email, global::System.String languageCode, global::System.String countryCode)
        {
            UserProfile userProfile = new UserProfile();
            userProfile.userId = userId;
            userProfile.userLogin = userLogin;
            userProfile.password = password;
            userProfile.firstName = firstName;
            userProfile.lastName = lastName;
            userProfile.email = email;
            userProfile.languageCode = languageCode;
            userProfile.countryCode = countryCode;
            return userProfile;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 userId
        {
            get
            {
                return _userId;
            }
            set
            {
                if (_userId != value)
                {
                    OnuserIdChanging(value);
                    ReportPropertyChanging("userId");
                    _userId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("userId");
                    OnuserIdChanged();
                }
            }
        }
        private global::System.Int64 _userId;
        partial void OnuserIdChanging(global::System.Int64 value);
        partial void OnuserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String userLogin
        {
            get
            {
                return _userLogin;
            }
            set
            {
                OnuserLoginChanging(value);
                ReportPropertyChanging("userLogin");
                _userLogin = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("userLogin");
                OnuserLoginChanged();
            }
        }
        private global::System.String _userLogin;
        partial void OnuserLoginChanging(global::System.String value);
        partial void OnuserLoginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String firstName
        {
            get
            {
                return _firstName;
            }
            set
            {
                OnfirstNameChanging(value);
                ReportPropertyChanging("firstName");
                _firstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("firstName");
                OnfirstNameChanged();
            }
        }
        private global::System.String _firstName;
        partial void OnfirstNameChanging(global::System.String value);
        partial void OnfirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String lastName
        {
            get
            {
                return _lastName;
            }
            set
            {
                OnlastNameChanging(value);
                ReportPropertyChanging("lastName");
                _lastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("lastName");
                OnlastNameChanged();
            }
        }
        private global::System.String _lastName;
        partial void OnlastNameChanging(global::System.String value);
        partial void OnlastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String languageCode
        {
            get
            {
                return _languageCode;
            }
            set
            {
                OnlanguageCodeChanging(value);
                ReportPropertyChanging("languageCode");
                _languageCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("languageCode");
                OnlanguageCodeChanged();
            }
        }
        private global::System.String _languageCode;
        partial void OnlanguageCodeChanging(global::System.String value);
        partial void OnlanguageCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String countryCode
        {
            get
            {
                return _countryCode;
            }
            set
            {
                OncountryCodeChanging(value);
                ReportPropertyChanging("countryCode");
                _countryCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("countryCode");
                OncountryCodeChanged();
            }
        }
        private global::System.String _countryCode;
        partial void OncountryCodeChanging(global::System.String value);
        partial void OncountryCodeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.WebMovies.Model", "FK_UserProfile_Country", "Country")]
        public Country Country
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Country>("Es.Udc.DotNet.WebMovies.Model.FK_UserProfile_Country", "Country").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Country>("Es.Udc.DotNet.WebMovies.Model.FK_UserProfile_Country", "Country").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Country> CountryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Country>("Es.Udc.DotNet.WebMovies.Model.FK_UserProfile_Country", "Country");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Country>("Es.Udc.DotNet.WebMovies.Model.FK_UserProfile_Country", "Country", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.WebMovies.Model", "FK_UserProfile_Language", "Language")]
        public Language Language
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Language>("Es.Udc.DotNet.WebMovies.Model.FK_UserProfile_Language", "Language").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Language>("Es.Udc.DotNet.WebMovies.Model.FK_UserProfile_Language", "Language").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Language> LanguageReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Language>("Es.Udc.DotNet.WebMovies.Model.FK_UserProfile_Language", "Language");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Language>("Es.Udc.DotNet.WebMovies.Model.FK_UserProfile_Language", "Language", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.WebMovies.Model", "FK_Link_UsrId", "Link")]
        public EntityCollection<Link> Links
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Link>("Es.Udc.DotNet.WebMovies.Model.FK_Link_UsrId", "Link");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Link>("Es.Udc.DotNet.WebMovies.Model.FK_Link_UsrId", "Link", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.WebMovies.Model", "FK_Rating_UsrId", "Rating")]
        public EntityCollection<Rating> Ratings
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Rating>("Es.Udc.DotNet.WebMovies.Model.FK_Rating_UsrId", "Rating");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Rating>("Es.Udc.DotNet.WebMovies.Model.FK_Rating_UsrId", "Rating", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.WebMovies.Model", "FK_Comment_UsrId", "Comment")]
        public EntityCollection<Comment> Comments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Comment>("Es.Udc.DotNet.WebMovies.Model.FK_Comment_UsrId", "Comment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Comment>("Es.Udc.DotNet.WebMovies.Model.FK_Comment_UsrId", "Comment", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.WebMovies.Model", "FK_Favorite_UsrId", "Favorite")]
        public EntityCollection<Favorite> Favorites
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Favorite>("Es.Udc.DotNet.WebMovies.Model.FK_Favorite_UsrId", "Favorite");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Favorite>("Es.Udc.DotNet.WebMovies.Model.FK_Favorite_UsrId", "Favorite", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
